### PR TITLE
fix: create multiple empty folders in root

### LINKED ISSUE #760: Creating a folder when there's an empty folder in the project fails

### PR DESCRIPTION
**Pull request by daavidrgz**
Closes #760

### CODE REVIEW

**Comment by daavidrgz** [comment]
I have read the CLA Document and I hereby sign the CLA

File: apps/web/src/components/Sidebar/Files/useTempNodes/index.ts [hunk 1]
```diff
@@ -112,7 +112,7 @@ export const useTempNodes = create<TmpFoldersState>((set, get) => ({
   },
   addToRootFolder: ({ path }) => {
     set((state) => {
-      const existingNodes = state.tmpFolders[path]
```
Comment (daavidrgz) [inline apps/web/src/components/Sidebar/Files/useTempNodes/index.ts:115]: `existingNodes` were erroneously obtained by indexing the `state.tmpFolders` with the newly created `path`. This always returned an empty content, deleting the previous nodes

**Comment by daavidrgz** [comment]
You're welcome! Awesome project in every aspect by the way, I'll keep contributing in my free time for sure
